services:
  - type: web
    name: quiz-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: ADMIN_PASSWORD
        scope: runtime
      - key: NODE_ENV
        value: production
        scope: runtime
